### ISSUE TITLE
Request to list more examples of what this does in the README

### ISSUE THREAD

**Issue by sethladd** [ScarabeiDart/ScarabeiDart#2]
Hi, thank you for publishing your package! Would you be willing to add more details to the README? Not sure what this does :)

Thank you!

**Comment by JFixby** [comment]
https://github.com/ScarabeiDart/ScarabeiDart/blob/master/scarabei/README.md

@sethladd Let me know if you have any questions.

**Comment by sethladd** [comment]
Thanks! Very helpful.

Curious, have you seen [Quiver](https://github.com/google/quiver-dart) and [path](https://pub.dartlang.org/packages/path) ?

**Comment by JFixby** [comment]
Basically, the ```Path``` package serves the purpose of overcoming issues related to the weak OOP design.

In Java, the file constructor taking String as an argument caused a lot of troubles and bugs. Long after it became obvious a Path.class was introduced to handle the issue, yet again it failed on the differences between POSIX and Windows.

Obviously, not every string represents a valid path. String is just a sequence of characters. Therefore there is no reason to model the path-concept with it.

A proper path-class will handle the differences between POSIX and Windows, and the whole ```Path```-package wouldn't exist at all, together with many bugs.

Another issue is that ```File``` is a more generic thing than just a local file. In addition to the local files, there could be in-memory file systems, remote, files inside zip archives or files on a web server available via the http.

Therefore, File implementations should not have public constructors, and instances should only be retrieved via a File-factory (FileSystem instance). This ensures that code that uses the File API can work with any implementation.

Scarabei is addressing all of it.

For example, copying files from a local file system to a S3Bucket in a pseudo code will be done in the following way:
```Java

File inputDir = ...;   // [local_FS]/home/user/ 
File outputDir = ...;  // [S3Bucket]/upload/

Iterable<File> filesList = inputDir.listAllChildren(); //all files from [local_FS]/home/user/*

Path inputPathPrefix = inputDir.getPath(); //   /home/user/
Path outputPathPrefix = outputDir.getPath();//  /upload/

FileSystem outputFileSystem = outputDir.getFileSystem();  //destination file system

...
for(File fileToCopy in filesList){
   Path inputPath = fileToCopy.getPath(); // take original file path '[local_FS]/home/user/x/y/1.txt'
   Path pathPostfix = inputPath.splitAt(inputPathPrefix.length); // detach the prefix making it '/x/y/1.txt'
   Path outputPath = outputPathPrefix.join(pathPostfix); // attach the postfix '[S3Bucket]/upload/x/y/1.txt'
   File outputFile = outputFileSystem.newFile(outputPath); // file system takes argument and creates new file at '[S3Bucket]/upload/x/y/1.txt'

   var bytes = fileToCopy.readBytes();//copy data
   outputFile.writebytes(bytes);//copy data
}
```

This code is quite generic and would work for any FileSystem (not only the local and S3Bucket ) as long as the file factory takes the Path as an argument to produce a File.

Also, it would take a lot more troubles to implement this using the ```Path``` and the ```dart.io```

I have not see the Quiver yet, but I will have a look at it.
